# Generated by Django 4.0.4 on 2022-05-25 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_delete_variant'),
        ('users', '0002_orders_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.delivery_address_details'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='note',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
