# Generated by Django 4.0.4 on 2022-05-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_item_order_product_alter_orders_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_address_details',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
