# Generated by Django 4.0.4 on 2022-05-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delivery_address_details_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_address_details',
            name='delivery_details',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
