# Generated by Django 4.0.4 on 2022-06-05 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_orders_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('cmpltcomplete', 'complete'), ('canceled', 'canceled'), ('pending', 'pending')], default='processing', max_length=20),
        ),
    ]
