# Generated by Django 4.0.4 on 2022-06-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_orders_date_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('complete', 'complete'), ('canceled', 'canceled'), ('pending', 'pending')], default='processing', max_length=20),
        ),
    ]
