# Generated by Django 4.0.4 on 2022-07-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_address_details',
            name='last_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='delivery_address_details',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
