# Generated by Django 4.0 on 2025-11-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_delivery_address_details_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_address_details',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
