# Generated by Django 4.0 on 2025-11-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_delivery_address_details_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
