# Generated by Django 4.0 on 2025-11-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_orders_currency_alter_orders_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('completed', 'completed'), ('canceled', 'canceled'), ('pending', 'pending')], default='processing', max_length=20),
        ),
    ]
