# Generated by Django 4.0 on 2025-11-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_orders_date_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('pending', 'pending')], default='processing', max_length=20),
        ),
    ]
