# Generated by Django 4.2.29 on 2026-03-12 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
