# Generated by Django 5.2 on 2026-03-19 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0009_shipping_method_cart_shipping_method"),
        ("users", "0015_alter_orders_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="shipping_label",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="orders",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cart.shipping_method",
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="shipping_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
