# Generated by Django 5.2.6 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_orders_shipping_label_orders_shipping_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='coupon_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
