# Generated by Django 3.2.8 on 2022-02-03 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model', to='shop.imagealbum'),
        ),
    ]
