# Generated by Django 3.2.8 on 2022-03-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20220203_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
