# Generated by Django 4.0 on 2022-03-16 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20220316_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model', to='shop.imagealbum'),
        ),
    ]
