# Generated by Django 3.2.8 on 2022-03-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
