# Generated by Django 4.0 on 2025-11-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_image_length_remove_image_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, related_name='products', to='shop.Categorie'),
        ),
    ]
