# Generated by Django 4.2.29 on 2026-03-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_rename_alt_image_alt_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tag', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='static/doobarashop/upload/images')),
                ('icon', models.CharField(blank=True, max_length=455)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('buton_text', models.CharField(blank=True, max_length=255)),
                ('lifirst', models.CharField(blank=True, max_length=255)),
                ('lesecond', models.CharField(blank=True, max_length=255)),
                ('lethird', models.CharField(blank=True, max_length=255)),
                ('lifirsti', models.CharField(blank=True, max_length=255)),
                ('lesecondi', models.CharField(blank=True, max_length=255)),
                ('lethirdi', models.CharField(blank=True, max_length=255)),
                ('classname', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
