# Generated by Django 4.2.29 on 2026-03-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_hero_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero_card',
            name='icon',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='hero_card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/doobarashop/upload/images'),
        ),
        migrations.AlterField(
            model_name='hero_card',
            name='lesecondi',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='hero_card',
            name='lethirdi',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='hero_card',
            name='lifirsti',
            field=models.CharField(blank=True, max_length=900),
        ),
    ]
