# Generated by Django 4.2.29 on 2026-03-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_hero_card_icon_alter_hero_card_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero_card',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
