# Generated by Django 4.2.29 on 2026-03-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_hero_card_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero_card',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
