# Generated by Django 4.2.29 on 2026-03-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_hero_card_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero_card',
            name='icon',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='hero_card',
            name='lesecondi',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='hero_card',
            name='lethirdi',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='hero_card',
            name='lifirsti',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
