# Generated by Django 4.2.29 on 2026-03-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_hero_card_icon_alter_hero_card_lesecondi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero_card',
            old_name='lesecondi',
            new_name='lisecondi',
        ),
        migrations.AddField(
            model_name='hero_card',
            name='categorie',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
