# Generated by Django 4.2.29 on 2026-03-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_rename_lesecondi_hero_card_lisecondi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero_card',
            old_name='lethirdi',
            new_name='lithirdi',
        ),
    ]
