# Generated by Django 4.2.29 on 2026-03-15 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_productimage_remove_product_album_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('advanced', 'Advanced'), ('pro', 'Pro')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('stock', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='products/variants/')),
                ('thumbnail', models.BooleanField(default=False)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariantItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='variant_list',
        ),
        migrations.AddField(
            model_name='product',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='VariantHolder',
        ),
        migrations.AddField(
            model_name='productvariantitem',
            name='included_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_in_variants', to='shop.product'),
        ),
        migrations.AddField(
            model_name='productvariantitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_items', to='shop.productvariant'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product'),
        ),
    ]
