# Generated by Django 4.2.29 on 2026-03-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_productvariant_productvariantimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantimage',
            name='image',
            field=models.ImageField(upload_to='static/doobarashop/upload/images'),
        ),
    ]
