# Generated by Django 5.2 on 2026-03-21 18:49

from django.db import migrations, models
from django.utils.text import slugify


def populate_product_slugs(apps, schema_editor):
    Product = apps.get_model("shop", "Product")

    for product in Product.objects.all().iterator():
        if product.slug:
            continue

        base_slug = slugify(product.name) or f"product-{product.pk}"
        slug_candidate = base_slug
        counter = 2

        while Product.objects.filter(slug=slug_candidate).exclude(pk=product.pk).exists():
            slug_candidate = f"{base_slug}-{counter}"
            counter += 1

        product.slug = slug_candidate
        product.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0026_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(populate_product_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
