# Generated by Django 5.2 on 2026-03-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0029_image_single_thumbnail_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/images/"),
        ),
        migrations.AlterField(
            model_name="productvariantimage",
            name="image",
            field=models.ImageField(upload_to="products/variants/images/"),
        ),
    ]
