# Generated by Django 5.2 on 2026-05-22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0032_productfeature_servicebadge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productfeature",
            name="icon",
            field=models.ImageField(
                blank=True,
                upload_to="product_features/icons/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["svg", "png", "webp", "jpg", "jpeg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="servicebadge",
            name="icon",
            field=models.ImageField(
                blank=True,
                upload_to="service_badges/icons/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["svg", "png", "webp", "jpg", "jpeg"]
                    )
                ],
            ),
        ),
    ]
