# Generated by Django 4.0 on 2022-01-11 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('child_node', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='doobarashop.categories')),
                ('right_node', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left', to='doobarashop.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('created_time', models.DateTimeField()),
                ('video', models.URLField()),
                ('stock', models.BooleanField()),
                ('featured', models.BooleanField()),
                ('variant', models.BooleanField()),
                ('active', models.BooleanField()),
                ('discount', models.BooleanField()),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doobarashop.categories')),
            ],
        ),
    ]
