# Generated by Django 3.2.8 on 2022-01-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doobarashop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='child_node',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='right_node',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='products', to='doobarashop.Categories'),
        ),
    ]
