# Generated by Django 3.2.8 on 2022-02-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20220204_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cart_item',
            name='cart',
            field=models.ManyToManyField(related_name='items', to='cart.Cart'),
        ),
    ]
