# Generated by ChatGPT Codex

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_productvariant_productvariantimage_and_more'),
        ('cart', '0007_alter_cart_item_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productvariant'),
        ),
    ]
