# Generated by Django 5.2 on 2026-03-19 18:11

import django.db.models.deletion
from django.db import migrations, models


def create_default_shipping_methods(apps, schema_editor):
    shipping_method = apps.get_model("cart", "Shipping_Method")
    shipping_method.objects.update_or_create(
        label="Pickup",
        defaults={
            "price": "0.00",
            "active": True,
            "sort_order": 1,
            "description": "Pickup — Free",
        },
    )
    shipping_method.objects.update_or_create(
        label="Delivery within 2 to 6 business days",
        defaults={
            "price": "5.00",
            "active": True,
            "sort_order": 2,
            "description": "Delivery within 2 to 6 business days — $5.00",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_cart_item_variant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipping_Method",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.AddField(
            model_name="cart",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carts",
                to="cart.shipping_method",
            ),
        ),
        migrations.RunPython(create_default_shipping_methods, migrations.RunPython.noop),
    ]
