# Generated by Django 5.2 on 2026-03-26 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0009_shipping_method_cart_shipping_method"),
        ("shop", "0031_normalproductvariant"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart_item",
            name="normal_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.normalproductvariant",
            ),
        ),
    ]
